services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ./db/.env
    container_name: postgres
    restart: always
    networks:
      - backend-network
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3001:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: next-app
    restart: always
    depends_on:
      - backend-user-management-service
    networks:
      - frontend-network
  backend-user-management-service:
    build:
      context: .
      dockerfile: ./backend/user_management_service/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./backend/user_management_service:/api
    env_file:
      - ./backend/user_management_service/.env
    container_name: user-management-service-api
    restart: always
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge