services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3333:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: next-app
    restart: always
    depends_on:
      - backend-user-management-service
    networks:
      - frontend-network
  user-db:
    build:
      context: .
      dockerfile: ./db/user/Dockerfile
    ports:
      - "5401:5432"
    env_file:
      - ./db/user/.env
    container_name: user-postgres
    restart: always
    networks:
      - backend-network
  cost-db:
    build:
      context: .
      dockerfile: ./db/cost/Dockerfile
    ports:
      - "5402:5432"
    env_file:
      - ./db/cost/.env
    container_name: cost-postgres
    restart: always
    networks:
      - backend-network
  backend-user-management-service:
    build:
      context: .
      dockerfile: ./backend/user_management_service/Dockerfile
    ports:
      - "8001:8080"
    volumes:
      - ./backend/user_management_service:/api
    env_file:
      - ./backend/user_management_service/.env
    container_name: user-management-service-api
    restart: always
    depends_on:
      - user-db
    networks:
      - backend-network
      - frontend-network
  backend-cost-management-service:
    build:
      context: .
      dockerfile: ./backend/cost_management_service/Dockerfile
    ports:
      - "8002:8080"
    volumes:
      - ./backend/cost_management_service:/api
    env_file:
      - ./backend/cost_management_service/.env
    container_name: cost-management-service-api
    restart: always
    depends_on:
      - cost-db
    networks:
      - backend-network
      - frontend-network
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge