services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgres
    restart: always
    networks:
      - backend-network
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3001:3000
    environment:
      NEXT_ENV: ${NEXT_ENV}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: next-app
    restart: always
    depends_on:
      - backend-user-manage
    networks:
      - frontend-network
  backend-user-manage:
    build:
      context: .
      dockerfile: ./backend/user_manage/Dockerfile
    ports:
      - "8081:8080"
    environment:
      GO_ENV: ${GO_ENV}
    container_name: user-manage-api
    restart: always
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge