name: Go CI

on:
    pull_request:
        branches:
            - main
            - develop
        paths:
            - 'backend/**'
    workflow_dispatch:

defaults:
    run:
        working-directory: backend

jobs:

    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go 1.22
          uses: actions/setup-go@v4
          with: 
            go-version: 1.22
        
        - name: Build
          run: go build -v ./...

        - name: Test
          run: go test -v ./...